#!/usr/bin/env python3
"""Build WokeHub.lua = Ace feature logic (no GUI) + the WOKE UI/wiring.

The Ace source mixes its own menu GUI in with the feature logic. This script
lifts out only the logic ranges, promotes the state/functions the UI needs from
chunk-locals to globals (the main chunk is already close to Lua's 200-local
limit, and the UI lives in its own function), and appends WokeHub_UI.lua.

Run:  python3 tools/build_wokehub.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "Ace_source.lua")
UI = os.path.join(ROOT, "WokeHub_UI.lua")
OUT = os.path.join(ROOT, "WokeHub.lua")

# Logic-only ranges of Ace_source.lua (1-indexed, inclusive).
#   1..3375     services, config, movement/steal/aimbot/counter/path logic
#   5350..6018  ESP, sky presets, performance + camera logic
#   7509..7586  auto-TP restore helpers and keybind repair
RANGES = [
    ("core feature logic", 1, 3375),
    ("visual / performance logic", 5350, 6018),
    ("auto-TP restore + keybind repair", 7509, 7586),
]

# Excluded on purpose (all GUI): 3376..5349 (menu build, rows, lightning FX),
# 6019..7508 (visuals/settings pages, steal bar, intro, notifications) and
# 7587..7895 (the Ace mobile button GUI).

# The chunk-level locals the UI layer needs to read and write.
GLOBALIZE_VARS = """
NS CS LAGGER_SPEED LAGGER_CARRY_SPEED currentSpeedMode
autoStealEnabled selectedStealMode autoStealRadius autoStealRadiusBox
selectedAimbotMode AIMBOT_SPEED LAGGER_AIMBOT_SPEED autoSwingEnabled
mirrorTPDownEnabled antiDesyncAutoSwingEnabled ANTI_DESYNC_AIMBOT_SPEED
batCounterEnabled medCounterEnabled antiKickEnabled setSafeModeVisual
autoResetOnMedEnabled espEnabled showTracerEnabled ragdollCountdownEnabled
fpsBoostEnabled antiLagVisualEnabled nukeOptimiserEnabled fovEnabled fovValue
noCamCollisionEnabled setAntiBodylockVisual customFontVisualEnabled skyTheme
setPlayerESPVisual setTracerESPVisual setRagdollCountdownVisual setFPSBoostVisual
setAntiLagVisual setNukeOptimiserVisual setFOVVisual setNoCamCollisionVisual
setCustomFontVisual skyValueLabel autoLeftEnabled autoRightEnabled
DEFAULT_SPEED_KEYBINDS DEFAULT_TP_DOWN_KEYBIND speedKeybinds speedKeybindButtons
listeningForSpeedKey autoTPEnabled autoTPHeight autoTPConn autoTPLastRun
autoTPClickDebounce tpDownKeybind tpDownKeybindButton listeningForTPDownKey
keybindListenStartedAt setAutoTPVisual dropBrainrotActive infJumpEnabled
antiRagdollEnabled antiRagdollConn unwalkEnabled unwalkSavedAnimate
hitHarderAnimEnabled hitHarderOriginalAnims selectedAnimationPack AnimationPacks
AnimationPackList AnimationPackIndex OriginalAnims HIT_HARDER_ANIMS
currentBackground aceGuiScaleValue aceProgressBarScaleValue refreshSpeedModeRows
""".split()

# Same, for `local function` declarations.
GLOBALIZE_FUNCS = """
doAutoTPDown startAutoTP stopAutoTP runTPFloor toggleAutoTP runDropBrainrot
applyAnimationPack setAntiRagdoll syncAnimationPackIndex
applySavedAnimationPackToCharacter getCurrentSpeedValue setSpeedMode
toggleCarryMode toggleLaggerMode
""".split()

# `local a, b, c` style declaration that must become global as a whole line.
GLOBALIZE_LINES = [
    "local enableUnwalk, disableUnwalk, enableHitHarderAnim, disableHitHarderAnim",
]

HEADER = """--[[
    WOKE — the hub UI driving the Ace feature logic.

    Generated by tools/build_wokehub.py — do not edit this file directly.
    Edit WokeHub_UI.lua (UI + wiring) or Ace_source.lua (feature logic) and
    rebuild.

    Contents:
      1. Feature logic lifted from Ace_source.lua (no GUI code from that file)
      2. The WOKE UI + the wiring that connects every button to that logic
]]

"""


def globalize(lines, remaining_vars, remaining_funcs, remaining_lines):
    """Strip `local ` from the chunk-level declarations the UI needs."""
    out = []
    for line in lines:
        m = re.match(r"^local function ([A-Za-z_]\w*)", line)
        if m and m.group(1) in remaining_funcs:
            remaining_funcs.discard(m.group(1))
            out.append(line[len("local "):])
            continue
        m = re.match(r"^local ([A-Za-z_]\w*)\b", line)
        if m and m.group(1) in remaining_vars:
            remaining_vars.discard(m.group(1))
            out.append(line[len("local "):])
            continue
        if line.strip() in remaining_lines:
            remaining_lines.discard(line.strip())
            # Forward declaration with no assignment: as globals they simply
            # start out nil, so the statement is dropped entirely.
            out.append("-- (forward declaration promoted to globals) " + line.strip())
            continue
        out.append(line)
    return out


def main():
    src = open(SOURCE, encoding="utf-8").read().split("\n")
    ui = open(UI, encoding="utf-8").read()

    remaining_vars = set(GLOBALIZE_VARS)
    remaining_funcs = set(GLOBALIZE_FUNCS)
    remaining_lines = set(GLOBALIZE_LINES)

    parts = [HEADER]
    for title, start, stop in RANGES:
        parts.append("--============================================================================--\n"
                     "-- ACE LOGIC: %s (Ace_source.lua %d-%d)\n"
                     "--============================================================================--\n" % (title, start, stop))
        chunk = globalize(src[start - 1:stop], remaining_vars, remaining_funcs, remaining_lines)
        # The 5350.. range starts inside a `do` block in the original file.
        if start == 5350:
            parts.append("do\n")
        parts.append("\n".join(chunk) + "\n")

    missing = sorted(remaining_vars | remaining_funcs | remaining_lines)
    if missing:
        raise SystemExit("build: declarations not found in Ace_source.lua: %s" % ", ".join(missing))

    parts.append("\n")
    parts.append(ui)

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))

    print("wrote %s (%d lines)" % (OUT, sum(p.count("\n") for p in parts)))


if __name__ == "__main__":
    sys.exit(main())
